package vu.lt.mybatis.model;

public class Course {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    private String courseName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.ID
     *
     * @return the value of PUBLIC.COURSE.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.ID
     *
     * @param id the value for PUBLIC.COURSE.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @return the value of PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public String getCourseName() {
        return courseName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.COURSE.COURSE_NAME
     *
     * @param courseName the value for PUBLIC.COURSE.COURSE_NAME
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public void setCourseName(String courseName) {
        this.courseName = courseName;
    }
}