package vu.lt.mybatis.model;

import java.util.List;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.STUDENT_NUMBER
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    private String studentNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    private Integer universityId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.ID
     *
     * @return the value of PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.ID
     *
     * @param id the value for PUBLIC.STUDENT.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.STUDENT_NUMBER
     *
     * @return the value of PUBLIC.STUDENT.STUDENT_NUMBER
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public String getStudentNumber() {
        return studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.STUDENT_NUMBER
     *
     * @param studentNumber the value for PUBLIC.STUDENT.STUDENT_NUMBER
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public void setStudentNumber(String studentNumber) {
        this.studentNumber = studentNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @return the value of PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public Integer getUniversityId() {
        return universityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @param universityId the value for PUBLIC.STUDENT.UNIVERSITY_ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public void setUniversityId(Integer universityId) {
        this.universityId = universityId;
    }



    public University university;
    public List<Course> courses;
}