package vu.lt.mybatis.model;

public class University {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.UNIVERSITY.UNIVERSITY_NAME
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    private String universityName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.ID
     *
     * @return the value of PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.ID
     *
     * @param id the value for PUBLIC.UNIVERSITY.ID
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.UNIVERSITY.UNIVERSITY_NAME
     *
     * @return the value of PUBLIC.UNIVERSITY.UNIVERSITY_NAME
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public String getUniversityName() {
        return universityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.UNIVERSITY.UNIVERSITY_NAME
     *
     * @param universityName the value for PUBLIC.UNIVERSITY.UNIVERSITY_NAME
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    public void setUniversityName(String universityName) {
        this.universityName = universityName;
    }
}