package vu.lt.mybatis.dao;

import vu.lt.mybatis.model.StudentCourse;

import java.util.List;
import org.mybatis.cdi.Mapper;

@Mapper
public interface StudentCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    int insert(StudentCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.STUDENT_COURSE
     *
     * @mbg.generated Sun Apr 28 20:52:24 EEST 2019
     */
    List<StudentCourse> selectAll();
}